
name: Build Android APK

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-24.04

    steps:
      - name: Download source code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,wasm32-unknown-unknown

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android components
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;27.2.12479018"

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Install project dependencies
        run: npm ci

      - name: Build WebAssembly
        run: npm run wasm

      - name: Initialize Android project
        run: npx tauri android init

      - name: Build APK
        run: npx tauri android build --apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: magium-recrystallized-android
          path: src-tauri/gen/android/app/build/outputs/apk/**/*.apk
          if-no-files-found: error
